version: "2.0"
services:
  wireguard:
    image: qmcgaw/gluetun:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY= # ZELF IN TE VULLEN
      - WIREGUARD_ADDRESSES= # ZELF IN TE VULLEN
      - SERVER_CITIES=Brussels
    ports:
      - 8001:8989 #Sonarr
      - 8002:7878 #Radarr
      - 8003:6767 #Bazarr
      - 8004:9696 #Prowlarr
      - 8005:9091 #Transmission
    restart: always

  transmission:
    image: linuxserver/transmission:latest
    network_mode: "service:wireguard"
    container_name: transmission
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - USER=admin
      - PASS=admin
    volumes:
      - ./transmission:/config
      - /media/hdd:/media/hdd
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    network_mode: "service:wireguard"
    container_name: sonarr
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./sonarr:/config
      - /media/hdd:/media/hdd #ExtraHDD
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    network_mode: "service:wireguard"
    container_name: radarr
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./radarr:/config
      - /media/hdd:/media/hdd #ExtraHDD
    restart: always

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    network_mode: "service:wireguard"
    container_name: bazarr
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./bazarr:/config
      - /media/hdd:/media/hdd #ExtraHDD
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    network_mode: "service:wireguard"
    container_name: prowlarr
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./prowlarr:/config
    restart: always

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./overseerr:/config
    ports:
      - 8006:5055
    restart: always

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./tautulli:/config
    ports:
      - 8007:8181
    restart: always

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - VERSION=docker
      - PLEX_CLAIM= #ZELF IN TE VULLEN
    volumes:
      - ./plex:/config
      - /media/hdd:/media/hdd
      - /dev/shm:/transcode #HARDWARE TRANSCODING
    ports:
      - 32400:32400
    devices:
      - /dev/dri:/dev/dri #HARDWARE TRANSCODING
    restart: always

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1