version: "2.0"
services:
  wireguard:
    image: linuxserver/wireguard:version-v1.0.20210914
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - "9091:9091/tcp"
      - 8000:9091 #Transmission
      - 8001:8989 #Sonarr
      - 8002:7878 #Radarr
      - 8003:6767 #Bazarr
      - 8004:9696 #Prowlarr
    volumes:
      - ./wg0.conf:/config/wg_confs/wg0.conf
      - /lib/modules:/lib/modules
    restart: always
  transmission:
    image: linuxserver/transmission:4.0.5
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    env_file:
      - ./transmission.env
    volumes:
      - ./transmission-config:/config
      - /media/hdd:/media/hdd
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./sonarr:/config
      - /media/hdd:/media/hdd #ExtraHDD
    network_mode: "service:wireguard"
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./radarr:/config
      - /media/hdd:/media/hdd #ExtraHDD
    network_mode: "service:wireguard"
    restart: always

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./bazarr:/config
      - /media/hdd:/media/hdd #ExtraHDD
    network_mode: "service:wireguard"
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./prowlarr:/config
    network_mode: "service:wireguard"
    restart: always

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./data:/config
    ports:
      - 8005:5055
    restart: always

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./data:/config
    ports:
      - 8006:8181
    restart: always

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./data:/config
      - /media/hdd/series:/tv
      - /media/hdd/films:/movies
    ports:
      - 32400:32400
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1