version: '3.8'

services:

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: always
    user: root
    ports:
      - 3030:3000
    environment:
      GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
    volumes:
      - ./srv/server_monitoring/data/grafana:/var/lib/grafana
      - ./srv/server_monitoring/data/grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./srv/server_monitoring/data/prometheus:/etc/prometheus.yml